### ISSUE TITLE
Add a first FAQ for WhereYouGo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo-website#3]
Mentioning the current limitations and workaround for the upcoming version

Generic:
 - [x] What credential do I need to use and for what purpose?
 - [x] What offline map files can be used in WhereYouGo?
 - [x] Google Signin to GC doesn't work with WYG	

Known bugs:
 - [x] Downloading cartridges fails although the login credentials are OK!
 - [x] Wherigo.com links are not opened with WhereYouGo anymore?
 - [x] No cartridges are found although I copied them to the correct folder!
 - [x] I can no longer use Locus as map provider in WhereYouGo!
 - [x] The text on the map is too small!

**Comment by Lineflyer** [comment]
Generic:
 - What credential do I need to use and for what purpose?
 - What offline map files can be used in WhereYouGo?
	
Known bugs:
 - Downloading cartridges fails although the login credentials are OK!
 - Wherigo.com links are not opened with WhereYouGo anymore?
 - No cartridges are found although I copied them to the correct folder!
 - When trying to load a savestate of a cartridge the app crashes!
 - I can no longer use Locus as map provider in WhereYouGo!
 - The text on the map is too small!

**Comment by ztNFny** [comment]
Google Signin to GC doesn't work with WYG
